# Generated by Django 3.1.3 on 2020-11-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('duration', models.FloatField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
    ]
