# Generated by Django 3.1.3 on 2020-11-05 06:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('excercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercise',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
